GRANT USAGE ON * . * TO 'valea'@'localhost' IDENTIFIED BY 'valea' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 ;

CREATE DATABASE `valea` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON `valea` . * TO 'valea'@'localhost' WITH GRANT OPTION;
